define(['../controller/StaffController'
        ,'../controller/MyStaffController'
        ,'../controller/ForgotController'
        ,'../controller/ChangepassController'
        ,'../controller/StaffFindController'
        ,'../controller/StaffPlanController'
        ,'../controller/StaffTrackingController'
        ,'../bonus/PersonalRateBonusController'
        ,'../bonus/PersonalStaticBonusController'
        ,'../bonus/PersonalStaticRateBonusController'
        ,'../bonus/ClassRateBonusController'
        ,'../bonus/ClassStaticBonusController'
        ,'../bonus/ClassStaticRateBonusController'
        ], function() {});
